[toolchain]
anchor_version = "0.31.1"

[features]
resolution = true
skip-lint = false

[programs.devnet]
managed_funds = "5g75VtkCiComNnhTtCjukVZ67peJosfbbvygMoFBGKXB"

[registry]
url = "https://api.apr.dev"

[provider]
# Use Helius devnet RPC for all Anchor operations
cluster = "https://devnet.helius-rpc.com/?api-key=19e2e36f-3222-481a-af0d-4271e77bb9b2"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
