[toolchain]
anchor_version = "0.31.1"

[features]
resolution = true
skip-lint = false

[programs.devnet]
managed_funds = "3dHDaKpa5aLMwimWJeBihqwQyyHpR6ky7NNDPtv7QFYt"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "${ANCHOR_PROVIDER_URL}"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
