[toolchain]
anchor_version = "0.31.1"

[features]
resolution = true
skip-lint = false

[programs.mainnet]
managed_funds = "DEFuNDoMVQ8TnYjDM95bJK55Myr5dmwor43xboG2XQYd"

[programs.devnet]
managed_funds = "DEFuNDoMVQ8TnYjDM95bJK55Myr5dmwor43xboG2XQYd"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "https://mainnet.helius-rpc.com/?api-key=19e2e36f-3222-481a-af0d-4271e77bb9b2"
wallet = "~/.config/solana/id_mainnet.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
