services:
  - type: web
    name: defunds-finance
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    healthCheckPath: /
    envVars:
      - key: NODE_ENV
        value: production
      - key: NODE_OPTIONS
        value: --max-old-space-size=512
      # Important: point the frontend API proxy to the backend service to avoid self-recursion
      # Set in Render dashboard to your backend public URL, e.g. https://defunds-backend.onrender.com
      # - key: BACKEND_URL
      #   value: https://<your-backend-host>
      # - key: NEXT_PUBLIC_BACKEND_URL
      #   value: https://<your-backend-host>
    domains:
      - defunds.finance
      - www.defunds.finance

  - type: web
    name: defunds-backend
    env: node
    plan: free
    buildCommand: npm install && npm -w apps/backend run build
    startCommand: node apps/backend/dist/index.js
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      # Required: set this in Render dashboard or via blueprint
      # - key: MONGODB_URI
      #   sync: false
      # Optional:
      # - key: SOLANA_RPC_URL
      #   sync: false

  - type: cron
    name: defunds-points-cron
    env: node
    schedule: "0 * * * *" # every hour at minute 0 (UTC)
    region: oregon
    buildCommand: npm install && npm -w apps/backend run build
    startCommand: node apps/backend/dist/scripts/runHourlyPoints.js
    envVars:
      - key: NODE_ENV
        value: production
      # Required in env: MONGODB_URI
      # Optional: SOLANA_RPC_URL

  - type: cron
    name: defunds-pnl-daily-cron
    env: node
    # Run once daily at 01:00 UTC
    schedule: "0 1 * * *"
    region: oregon
    buildCommand: npm install && npm -w apps/backend run build
    startCommand: node apps/backend/dist/scripts/runDailyPnl.js
    envVars:
      - key: NODE_ENV
        value: production
      